### ISSUE TITLE
Does this work with current Xamarin 8.1.1, Xcode 10.2.1? Crashes for me.

### ISSUE THREAD

**Issue by trevoriancox** [Sankra/Xnapshot#3]
Here's part of the output I get:

```
Running command. { Path: "sh", Arguments: "-c "otool -o '.../zxing.portable.dll' | grep CalabashServer"", CurrentDirectory: "/Users/trevorcox/Documents/src/ftx3.lane2/FunTimes3" }
Finished with exit code 1 in 39 ms.
llvm-objdump: '.../zxing.portable.dll': Object is not a Mach-O file type.

Starting app bundle.  { AppBundle: "....iOS.app" }
Finished with exit code 0 in 1726 ms.
Known Devices:
Apple TV (12.2) [...] (Simulator)

Running command. { Path: "ps", Arguments: "-xww -o pid,user,args", CurrentDirectory: "..." }
Finished with exit code 0 in 44 ms.

(process list dump due to crash)

Uncaught exception handling
```

**Comment by hjerpbakk** [comment]
Thanks for letting me know, I will test and get back to you.

**Comment by hjerpbakk** [comment]
I've verified that Xnapshot works with the following combination of iOS 12.2, Xcode 10.2.1 and Xamarin.iOS 8.1 @trevoriancox . I needed to update the device parser logic however, been in the backlog since forever, and enable support for up to 10 screenshots. I hope to finish this work by noon tomorrow, CET.

**Comment by hjerpbakk** [comment]
Now you can try version 2.0 @trevoriancox , [Nuget-package 2.0.12 or later should work](https://www.nuget.org/packages/Xnapshot/2.0.12). The [readme is updated](https://github.com/Sankra/Xnapshot#from-1x-to-20) to reflect the needed changes.

**Comment by trevoriancox** [comment]
I've resolved this by copying the Xnapshot.Example.Usage project into my solution, and changing the reference to use Xnapshot 2.0.13 from Nuget.
